### ISSUE TITLE
Formulaire d'inscription

### ISSUE THREAD

**Issue by j15e** [webaquebec/openhack#10]
Je suggère un tarif de 20$ pour que le monde se commettre un peu et poser les 3 questions suivantes :

```
- À quel(s) projet(s) souhaitez-vous contribuer? 
(champs texte)

- Quel jour(s) serez-vous présent?
 (samedi et dimanche, samedi seulement, dimanche seulement)

- Quel est votre niveau de connaissance du projet? 
(un peu, pas mal, beaucoup, je suis le créateur)
```

**Comment by j15e** [comment]
On me rappel que les étudiants sont paumé (même s'il vont toujours au starbar) alors peut-être que c'est juste plus simple de mettre ça gratuit. Côté financement j'aurai pas de problème à m'arranger avec des commanditaires et le WAQ.

**Comment by L-A** [comment]
Ça serait possible de demander si la personne est étudiante, et charger seulement si c'est le cas? Long shot, mais ça règlerait notre question de prévoir l'engagement et la quantité de personnes.

**Comment by j15e** [comment]
Je vais attendre le feedback de tout le monde (pour les questions aussi) et je vais m'arranger pour ajouter un box EventBrite pour lundi max et lancer ça officiellement dans les canaux du WAQ.

Je vais aussi une fois que ce sera officiel faire un petite tournée auprès des écoles pour inviter les étudiants.

**Comment by j15e** [comment]
Ça s'enligne pour ça (5$ + 3 questions difficiles) :

![capture decran 2014-02-02 a 14 07 33](https://f.cloud.github.com/assets/143380/2061032/51803edc-8c3d-11e3-9a53-121c6385a09b.png)

**Comment by garno** [comment]
Ça serait bien de préciser que l'on peut travailler sur n'importe quel projet open source et pas nécessairement sur ceux listés.

**Comment by j15e** [comment]
Ouai je pourrais ajouter "Autre (préciser)"

**Comment by remi** [comment]
Même pas besoin de préciser, je vois très bien des gens qui veulent juste s’inscrire et décider là-bas de sur quoi ils vont travailler.

**Comment by j15e** [comment]
Ok ceci (j'ai aussi enlevé le obligatoire des 2 dernières questions) : 

![capture decran 2014-02-02 a 14 17 03](https://f.cloud.github.com/assets/143380/2061043/ab3bec72-8c3e-11e3-9409-f5979da4ef9e.png)

**Comment by remi** [comment]
:+1:

**Comment by garno** [comment]
:+1:
