### ISSUE TITLE
Volet compétition données ouverte à ajouter ~

### ISSUE THREAD

**Issue by j15e** [webaquebec/openhack#12]
Faudrait comme une 3ème section "Compétition" ou un projet "Spécial" parce qu'on va ajouter à l'événement une compétition sur les données ouvertes avec la ville pour les intéressés. Je suis pas très chaud à l'idée mais.

**Comment by j15e** [comment]
Peut-être qu'on peut suggérer autre chose? La ville m'a parlé de changer le portal de données ouvertes actuelle pour utiliser deux nouvelles choses :

http://ckan.org/
https://github.com/GSA/data.gov

Il me semble que ça serait plus nice/pertient de donner un prix de X000$ à une équipe de gens qui voudrait faire une implantation / un setup nice pour la ville de Québec durant le weekend que de faire une application avec un set de données?

**Comment by L-A** [comment]
Je comprends. Est-ce que ça serait ouvert à dire mettons "Projets des commanditaires" et annoncer le contexte et les prix pour chacun?

Si la Ville peut nous donner quelques objectifs autour desquels se lancer, ça serait plus pertinent que "faites quelque chose avec les données".

**Comment by remi** [comment]
> Est-ce que ça serait ouvert à dire mettons "Projets des commanditaires" et annoncer le contexte et les prix pour chacun?

Je serais d’accord avec cette idée.

> Si la Ville peut nous donner quelques objectifs autour desquels se lancer, ça serait plus pertinent que "faites quelque chose avec les données".

Effectivement.

**Comment by j15e** [comment]
Oui en effet on pourrait appeler ça comme ça! Je vais avoir une explication plus détaillée sous peu.

**Comment by L-A** [comment]
Rémi Prévost, approbateur agréé.

**Comment by remi** [comment]
> Rémi Prévost, approbateur agréé.

:+1:

**Comment by j15e** [comment]
Il va y avoir 2 choses qui vont s'ajouter via la ville en fait :
- Un projet à contribuer qui sera l'implantation CKAN/data.gov pour la ville de Québec/Sherbrooke (eux ont déjà commencé à l'implanter et on va essayer de les inviter à venir). Cet élément là va bien fitter avec l'événement.
- Une compétition de données ouverte

**Comment by L-A** [comment]
On a les grandes lignes de la «compétition» ?

**Comment by j15e** [comment]
Na, je l'avais sur un EventBrite qu'ils avaient fait temporairement mais il a été supprimé, je vais recevoir ça d'ici la fin de la semaine, j'ajoute ça ici dès que je l'ai.

Tout ça me fait penser que ça pourrait être cool d'avoir des entreprises qui commandite des projets OpenSource pour l'événement, genre Hookt commandite le développement qui sera fait sur Capistrano 3. Mais je sais pas vraiment ce que ça donnerait (outre financer l'événement), avez-vous des idées? Ou let's keep it personal?

**Comment by jipiboily** [comment]
En lisant ce thread, me vient en tête: "bounty list". La ville pourrait p-e avoir une liste d'élément et des prix qu'ils paieraient pour, mais il pourrait y avoir des commanditaires comme @j15e le dit. Finalement, il y a déjà ce genre de bounty list sur les internets pour des projets open source parfois. Je ne me souviens plus trop où, mais il y en a au moins quelques unes. Just saying...:)

**Comment by L-A** [comment]
À mon avis, c'est une très bonne idée. Une liste comme ça permet à différentes personnes de se regrouper autour d'un but clair, et surtout, à chaque groupe de travailler sur un objectif différent et désirable.

**Comment by remi** [comment]
> En lisant ce thread, me vient en tête: "bounty list". La ville pourrait p-e avoir une liste d'élément et des prix qu'ils paieraient pour, mais il pourrait y avoir des commanditaires comme @j15e le dit.

Ce n’est pas une mauvaise idée. Ça les aiderait peut-être à prioriser leur demandes et ça augmenterait certainement la motivation des participants (you know, des tâches associés à des montants en :dollar:).

**Comment by jipiboily** [comment]
Ha voilà, j'ai retrouvé le site spécifique que j'avais en tête. Je n'ai aucune idée des détails du fonctionnement, mais voici: https://www.bountysource.com/bounties/search?direction=desc&order=bounty_total&per_page=50&page=1  (la recherche est vraiment, vraiment lente. P-e un PR à faire là? héhé)

Ils ont beaucoup plus de _bounty_ que dans mon souvenir!

http://www.codetriage.com/ est nice aussi, mais y'a pas d'argent là. Ceci dit, les :dollar: ne devraient pas être la seule motivation pour de l'Open Source en théorie, mais si ça peut aider, pourquoi pas!

**Comment by L-A** [comment]
> les :dollar: ne devraient pas être la seule motivation pour de l'Open Source en théorie

Données ouvertes ≠ open source. Faut pas oublier ;)

**Comment by remi** [comment]
> Ceci dit, les :dollar: ne devraient pas être la seule motivation pour de l'Open Source en théorie

Je ne vois pas vraiment ça comme de l’Open Source, mais plutôt comme une organisation (la Ville de Québec) qui nous demande d’utiliser leurs données.

**Comment by jipiboily** [comment]
Right, mixing two things, here :)

J'avais aussi en tête la partie open source, mais vous avez raison.

**Comment by j15e** [comment]
Bon au final on va les accueillir, ce sera dimanche seulement, et l'inscription se fait à part pour participer au Hackaton. J'ai fait un ajout rapido vu qu'ils ont annoncé ça déjà ce matin, mais ça pourrait être amélioré. Je vais voir si on pourrait pas au moins mettre ça dans le même EventBrite parce que ça fait compliqué un peu, quoi que c'est bien que ce soit clairement séparé.

![hackaton](https://f.cloud.github.com/assets/143380/2219495/5a695b66-9a41-11e3-80c2-f40cf6813e6b.png)

**Comment by jipiboily** [comment]
:+1:

**Comment by j15e** [comment]
BTW, scope : ils vont ouvrir en Open Source et présenter leur projet d'application mobile pour la gestion des parking de la Ville de Québec (disponibilité, paiement, etc). Il v a y avoir des prix pour des features, du design proposé, etc. Je vais annoncer ça d'ici quelques jours max.

ALSO : leur 2ème ronde va se passer à la nouvelle biblio Monique-Corriveau super moderne et ils aimerait tenir des présentations ala OpenCode alors je leur ai dit de vous contacter @remiprev @garno voir si il pourrait pas y avoir une édition spécial du Open Code à cet endroit ou quelconque lien à faire. 

![capture decran 2014-02-20 a 10 38 51](https://f.cloud.github.com/assets/143380/2219752/217ce94a-9a45-11e3-9b2d-8796bd63bb4f.png)

http://capitaleouverte.org/2014/02/tournoi-hackathon-des-donnees-ouvertes-les-22-et-29-mars/?utm_content=buffer8a8e0&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by remi** [comment]
![](http://i.imgur.com/qhyJ4ZQ.gif)

**Comment by L-A** [comment]
Gros thumbs up pour mettre un prix séparé sur certaines features/besoins, si c'est bien ce que tu décris.

C'est plus sain de diviser le travail dans plusieurs directions constructives que de demander à toutes les équipes de travailler gratuitement au bénéfice d'une seule organisation.

TL;DR Le spec work c'est mal.

**Comment by j15e** [comment]
Oui il regarde avec le client (le département de la ville concerné) pour déterminer des prix séparés pour des demandes distinctes.
