### ISSUE TITLE
Ajout de campagne-en-ligne de Centraide Québec

### ISSUE THREAD

**Issue by nicolasroberge** [webaquebec/openhack#14]
Bonjour, @centraide-quebec voudrait savoir si son projet de campagne-en-ligne serait admissible au OpenHack. Si oui, sera-t-il possible de le présenter aux participants?

https://github.com/centraide-quebec/campagne-en-ligne

**Comment by remi** [comment]
1. C’est un projet open-source, alors pourquoi pas?
2. Si une personne désire le présenter, pourquoi pas?

**Comment by j15e** [comment]
Salut, j'ai vu que malheureusement ni Bernard ni Eric ne sont disponible, mais ça pourrait quand même être intéressant de présenter le projet et discuter de l'initiative avec les gens présent.

**Comment by nicolasroberge** [comment]
Je ne pourrai pas le présenter officiellement avec Centraide. Ils n'ont pas
pu se rendre disponible pour l'événement.

Le 17 mars 2014 09:58, Jean-Philippe Doyle notifications@github.com a
écrit :

> Salut, j'ai vu que malheureusement ni Bernard ni Eric ne sont disponible,
> mais ça pourrait quand même être intéressant de présenter le projet et
> discuter de l'initiative avec les gens présent.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/qcnum/openhack/issues/14#issuecomment-37817632
> .

## 

*Nicolas Roberge *Président et conseiller en affaires électroniques

http://evollia.com/

QC     418-907-9292
MTL   514-357-2135
CELL 418-573-7879

45, rue Dalhousie
Québec (QC) G1K 8S3

http://www.linkedin.com/company/evollia?trk=company_logohttps://twitter.com/evolliawebhttps://www.facebook.com/evolliawebhttps://plus.google.com/u/0/105810587855531439171/posts
