### ISSUE TITLE
Don't group presentations/subjects by day.

### ISSUE THREAD

**Issue by L-A** [webaquebec/openhack#5]
Je vais prévoir des tags samedi/dimanche à mettre individuellement sur les présentations à la place.

**Comment by j15e** [comment]
Bon plan!

**Comment by antoineleclair** [comment]
Vous pourrez enlever ma précision sur la possibilité du dimanche dans ce cas.

**Comment by L-A** [comment]
Got it. Je vais sûrement classer selon projets et présentations à la place. @j15e avait fait ça initialement et c'était pas une mauvaise idée.

**Comment by remi** [comment]
Excellente idée :+1:
